/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as authSignupImport } from './routes/(auth)/signup'
import { Route as authSigninImport } from './routes/(auth)/signin'
import { Route as DashboardOrganizationsRouteImport } from './routes/dashboard/organizations/route'
import { Route as DashboardAdministrationRouteImport } from './routes/dashboard/administration/route'
import { Route as DashboardOrganizationsIndexImport } from './routes/dashboard/organizations/index'
import { Route as DashboardAdministrationIndexImport } from './routes/dashboard/administration/index'
import { Route as DashboardOrganizationsAddRouteImport } from './routes/dashboard/organizations/add/route'
import { Route as DashboardOrganizationsOrganizationIdRouteImport } from './routes/dashboard/organizations/$organizationId/route'
import { Route as DashboardAdministrationUsersRouteImport } from './routes/dashboard/administration/users/route'
import { Route as DashboardOrganizationsAddIndexImport } from './routes/dashboard/organizations/add/index'
import { Route as DashboardOrganizationsOrganizationIdIndexImport } from './routes/dashboard/organizations/$organizationId/index'
import { Route as DashboardAdministrationUsersIndexImport } from './routes/dashboard/administration/users/index'
import { Route as DashboardOrganizationsOrganizationIdEditRouteImport } from './routes/dashboard/organizations/$organizationId/edit/route'
import { Route as DashboardAdministrationUsersAddRouteImport } from './routes/dashboard/administration/users/add/route'
import { Route as DashboardAdministrationUsersUserIdRouteImport } from './routes/dashboard/administration/users/$userId/route'
import { Route as DashboardOrganizationsOrganizationIdEditIndexImport } from './routes/dashboard/organizations/$organizationId/edit/index'
import { Route as DashboardAdministrationUsersAddIndexImport } from './routes/dashboard/administration/users/add/index'
import { Route as DashboardAdministrationUsersUserIdIndexImport } from './routes/dashboard/administration/users/$userId/index'
import { Route as DashboardAdministrationUsersUserIdEditRouteImport } from './routes/dashboard/administration/users/$userId/edit/route'
import { Route as DashboardAdministrationUsersUserIdEditIndexImport } from './routes/dashboard/administration/users/$userId/edit/index'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const authSignupRoute = authSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)

const authSigninRoute = authSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)

const DashboardOrganizationsRouteRoute =
  DashboardOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardAdministrationRouteRoute =
  DashboardAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardAdministrationIndexRoute =
  DashboardAdministrationIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdministrationRouteRoute,
  } as any)

const DashboardOrganizationsAddRouteRoute =
  DashboardOrganizationsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsOrganizationIdRouteRoute =
  DashboardOrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardAdministrationUsersRouteRoute =
  DashboardAdministrationUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => DashboardAdministrationRouteRoute,
  } as any)

const DashboardOrganizationsAddIndexRoute =
  DashboardOrganizationsAddIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsAddRouteRoute,
  } as any)

const DashboardOrganizationsOrganizationIdIndexRoute =
  DashboardOrganizationsOrganizationIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsOrganizationIdRouteRoute,
  } as any)

const DashboardAdministrationUsersIndexRoute =
  DashboardAdministrationUsersIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdministrationUsersRouteRoute,
  } as any)

const DashboardOrganizationsOrganizationIdEditRouteRoute =
  DashboardOrganizationsOrganizationIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardOrganizationsOrganizationIdRouteRoute,
  } as any)

const DashboardAdministrationUsersAddRouteRoute =
  DashboardAdministrationUsersAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => DashboardAdministrationUsersRouteRoute,
  } as any)

const DashboardAdministrationUsersUserIdRouteRoute =
  DashboardAdministrationUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => DashboardAdministrationUsersRouteRoute,
  } as any)

const DashboardOrganizationsOrganizationIdEditIndexRoute =
  DashboardOrganizationsOrganizationIdEditIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsOrganizationIdEditRouteRoute,
  } as any)

const DashboardAdministrationUsersAddIndexRoute =
  DashboardAdministrationUsersAddIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdministrationUsersAddRouteRoute,
  } as any)

const DashboardAdministrationUsersUserIdIndexRoute =
  DashboardAdministrationUsersUserIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdministrationUsersUserIdRouteRoute,
  } as any)

const DashboardAdministrationUsersUserIdEditRouteRoute =
  DashboardAdministrationUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardAdministrationUsersUserIdRouteRoute,
  } as any)

const DashboardAdministrationUsersUserIdEditIndexRoute =
  DashboardAdministrationUsersUserIdEditIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdministrationUsersUserIdEditRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/administration': {
      id: '/dashboard/administration'
      path: '/administration'
      fullPath: '/dashboard/administration'
      preLoaderRoute: typeof DashboardAdministrationRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/organizations': {
      id: '/dashboard/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DashboardOrganizationsRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupImport
      parentRoute: typeof authRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/administration/users': {
      id: '/dashboard/administration/users'
      path: '/users'
      fullPath: '/dashboard/administration/users'
      preLoaderRoute: typeof DashboardAdministrationUsersRouteImport
      parentRoute: typeof DashboardAdministrationRouteImport
    }
    '/dashboard/organizations/$organizationId': {
      id: '/dashboard/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/dashboard/organizations/$organizationId'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdRouteImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/add': {
      id: '/dashboard/organizations/add'
      path: '/add'
      fullPath: '/dashboard/organizations/add'
      preLoaderRoute: typeof DashboardOrganizationsAddRouteImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/administration/': {
      id: '/dashboard/administration/'
      path: '/'
      fullPath: '/dashboard/administration/'
      preLoaderRoute: typeof DashboardAdministrationIndexImport
      parentRoute: typeof DashboardAdministrationRouteImport
    }
    '/dashboard/organizations/': {
      id: '/dashboard/organizations/'
      path: '/'
      fullPath: '/dashboard/organizations/'
      preLoaderRoute: typeof DashboardOrganizationsIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/administration/users/$userId': {
      id: '/dashboard/administration/users/$userId'
      path: '/$userId'
      fullPath: '/dashboard/administration/users/$userId'
      preLoaderRoute: typeof DashboardAdministrationUsersUserIdRouteImport
      parentRoute: typeof DashboardAdministrationUsersRouteImport
    }
    '/dashboard/administration/users/add': {
      id: '/dashboard/administration/users/add'
      path: '/add'
      fullPath: '/dashboard/administration/users/add'
      preLoaderRoute: typeof DashboardAdministrationUsersAddRouteImport
      parentRoute: typeof DashboardAdministrationUsersRouteImport
    }
    '/dashboard/organizations/$organizationId/edit': {
      id: '/dashboard/organizations/$organizationId/edit'
      path: '/edit'
      fullPath: '/dashboard/organizations/$organizationId/edit'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdEditRouteImport
      parentRoute: typeof DashboardOrganizationsOrganizationIdRouteImport
    }
    '/dashboard/administration/users/': {
      id: '/dashboard/administration/users/'
      path: '/'
      fullPath: '/dashboard/administration/users/'
      preLoaderRoute: typeof DashboardAdministrationUsersIndexImport
      parentRoute: typeof DashboardAdministrationUsersRouteImport
    }
    '/dashboard/organizations/$organizationId/': {
      id: '/dashboard/organizations/$organizationId/'
      path: '/'
      fullPath: '/dashboard/organizations/$organizationId/'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdIndexImport
      parentRoute: typeof DashboardOrganizationsOrganizationIdRouteImport
    }
    '/dashboard/organizations/add/': {
      id: '/dashboard/organizations/add/'
      path: '/'
      fullPath: '/dashboard/organizations/add/'
      preLoaderRoute: typeof DashboardOrganizationsAddIndexImport
      parentRoute: typeof DashboardOrganizationsAddRouteImport
    }
    '/dashboard/administration/users/$userId/edit': {
      id: '/dashboard/administration/users/$userId/edit'
      path: '/edit'
      fullPath: '/dashboard/administration/users/$userId/edit'
      preLoaderRoute: typeof DashboardAdministrationUsersUserIdEditRouteImport
      parentRoute: typeof DashboardAdministrationUsersUserIdRouteImport
    }
    '/dashboard/administration/users/$userId/': {
      id: '/dashboard/administration/users/$userId/'
      path: '/'
      fullPath: '/dashboard/administration/users/$userId/'
      preLoaderRoute: typeof DashboardAdministrationUsersUserIdIndexImport
      parentRoute: typeof DashboardAdministrationUsersUserIdRouteImport
    }
    '/dashboard/administration/users/add/': {
      id: '/dashboard/administration/users/add/'
      path: '/'
      fullPath: '/dashboard/administration/users/add/'
      preLoaderRoute: typeof DashboardAdministrationUsersAddIndexImport
      parentRoute: typeof DashboardAdministrationUsersAddRouteImport
    }
    '/dashboard/organizations/$organizationId/edit/': {
      id: '/dashboard/organizations/$organizationId/edit/'
      path: '/'
      fullPath: '/dashboard/organizations/$organizationId/edit/'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdEditIndexImport
      parentRoute: typeof DashboardOrganizationsOrganizationIdEditRouteImport
    }
    '/dashboard/administration/users/$userId/edit/': {
      id: '/dashboard/administration/users/$userId/edit/'
      path: '/'
      fullPath: '/dashboard/administration/users/$userId/edit/'
      preLoaderRoute: typeof DashboardAdministrationUsersUserIdEditIndexImport
      parentRoute: typeof DashboardAdministrationUsersUserIdEditRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardAdministrationUsersUserIdEditRouteRouteChildren {
  DashboardAdministrationUsersUserIdEditIndexRoute: typeof DashboardAdministrationUsersUserIdEditIndexRoute
}

const DashboardAdministrationUsersUserIdEditRouteRouteChildren: DashboardAdministrationUsersUserIdEditRouteRouteChildren =
  {
    DashboardAdministrationUsersUserIdEditIndexRoute:
      DashboardAdministrationUsersUserIdEditIndexRoute,
  }

const DashboardAdministrationUsersUserIdEditRouteRouteWithChildren =
  DashboardAdministrationUsersUserIdEditRouteRoute._addFileChildren(
    DashboardAdministrationUsersUserIdEditRouteRouteChildren,
  )

interface DashboardAdministrationUsersUserIdRouteRouteChildren {
  DashboardAdministrationUsersUserIdEditRouteRoute: typeof DashboardAdministrationUsersUserIdEditRouteRouteWithChildren
  DashboardAdministrationUsersUserIdIndexRoute: typeof DashboardAdministrationUsersUserIdIndexRoute
}

const DashboardAdministrationUsersUserIdRouteRouteChildren: DashboardAdministrationUsersUserIdRouteRouteChildren =
  {
    DashboardAdministrationUsersUserIdEditRouteRoute:
      DashboardAdministrationUsersUserIdEditRouteRouteWithChildren,
    DashboardAdministrationUsersUserIdIndexRoute:
      DashboardAdministrationUsersUserIdIndexRoute,
  }

const DashboardAdministrationUsersUserIdRouteRouteWithChildren =
  DashboardAdministrationUsersUserIdRouteRoute._addFileChildren(
    DashboardAdministrationUsersUserIdRouteRouteChildren,
  )

interface DashboardAdministrationUsersAddRouteRouteChildren {
  DashboardAdministrationUsersAddIndexRoute: typeof DashboardAdministrationUsersAddIndexRoute
}

const DashboardAdministrationUsersAddRouteRouteChildren: DashboardAdministrationUsersAddRouteRouteChildren =
  {
    DashboardAdministrationUsersAddIndexRoute:
      DashboardAdministrationUsersAddIndexRoute,
  }

const DashboardAdministrationUsersAddRouteRouteWithChildren =
  DashboardAdministrationUsersAddRouteRoute._addFileChildren(
    DashboardAdministrationUsersAddRouteRouteChildren,
  )

interface DashboardAdministrationUsersRouteRouteChildren {
  DashboardAdministrationUsersUserIdRouteRoute: typeof DashboardAdministrationUsersUserIdRouteRouteWithChildren
  DashboardAdministrationUsersAddRouteRoute: typeof DashboardAdministrationUsersAddRouteRouteWithChildren
  DashboardAdministrationUsersIndexRoute: typeof DashboardAdministrationUsersIndexRoute
}

const DashboardAdministrationUsersRouteRouteChildren: DashboardAdministrationUsersRouteRouteChildren =
  {
    DashboardAdministrationUsersUserIdRouteRoute:
      DashboardAdministrationUsersUserIdRouteRouteWithChildren,
    DashboardAdministrationUsersAddRouteRoute:
      DashboardAdministrationUsersAddRouteRouteWithChildren,
    DashboardAdministrationUsersIndexRoute:
      DashboardAdministrationUsersIndexRoute,
  }

const DashboardAdministrationUsersRouteRouteWithChildren =
  DashboardAdministrationUsersRouteRoute._addFileChildren(
    DashboardAdministrationUsersRouteRouteChildren,
  )

interface DashboardAdministrationRouteRouteChildren {
  DashboardAdministrationUsersRouteRoute: typeof DashboardAdministrationUsersRouteRouteWithChildren
  DashboardAdministrationIndexRoute: typeof DashboardAdministrationIndexRoute
}

const DashboardAdministrationRouteRouteChildren: DashboardAdministrationRouteRouteChildren =
  {
    DashboardAdministrationUsersRouteRoute:
      DashboardAdministrationUsersRouteRouteWithChildren,
    DashboardAdministrationIndexRoute: DashboardAdministrationIndexRoute,
  }

const DashboardAdministrationRouteRouteWithChildren =
  DashboardAdministrationRouteRoute._addFileChildren(
    DashboardAdministrationRouteRouteChildren,
  )

interface DashboardOrganizationsOrganizationIdEditRouteRouteChildren {
  DashboardOrganizationsOrganizationIdEditIndexRoute: typeof DashboardOrganizationsOrganizationIdEditIndexRoute
}

const DashboardOrganizationsOrganizationIdEditRouteRouteChildren: DashboardOrganizationsOrganizationIdEditRouteRouteChildren =
  {
    DashboardOrganizationsOrganizationIdEditIndexRoute:
      DashboardOrganizationsOrganizationIdEditIndexRoute,
  }

const DashboardOrganizationsOrganizationIdEditRouteRouteWithChildren =
  DashboardOrganizationsOrganizationIdEditRouteRoute._addFileChildren(
    DashboardOrganizationsOrganizationIdEditRouteRouteChildren,
  )

interface DashboardOrganizationsOrganizationIdRouteRouteChildren {
  DashboardOrganizationsOrganizationIdEditRouteRoute: typeof DashboardOrganizationsOrganizationIdEditRouteRouteWithChildren
  DashboardOrganizationsOrganizationIdIndexRoute: typeof DashboardOrganizationsOrganizationIdIndexRoute
}

const DashboardOrganizationsOrganizationIdRouteRouteChildren: DashboardOrganizationsOrganizationIdRouteRouteChildren =
  {
    DashboardOrganizationsOrganizationIdEditRouteRoute:
      DashboardOrganizationsOrganizationIdEditRouteRouteWithChildren,
    DashboardOrganizationsOrganizationIdIndexRoute:
      DashboardOrganizationsOrganizationIdIndexRoute,
  }

const DashboardOrganizationsOrganizationIdRouteRouteWithChildren =
  DashboardOrganizationsOrganizationIdRouteRoute._addFileChildren(
    DashboardOrganizationsOrganizationIdRouteRouteChildren,
  )

interface DashboardOrganizationsAddRouteRouteChildren {
  DashboardOrganizationsAddIndexRoute: typeof DashboardOrganizationsAddIndexRoute
}

const DashboardOrganizationsAddRouteRouteChildren: DashboardOrganizationsAddRouteRouteChildren =
  {
    DashboardOrganizationsAddIndexRoute: DashboardOrganizationsAddIndexRoute,
  }

const DashboardOrganizationsAddRouteRouteWithChildren =
  DashboardOrganizationsAddRouteRoute._addFileChildren(
    DashboardOrganizationsAddRouteRouteChildren,
  )

interface DashboardOrganizationsRouteRouteChildren {
  DashboardOrganizationsOrganizationIdRouteRoute: typeof DashboardOrganizationsOrganizationIdRouteRouteWithChildren
  DashboardOrganizationsAddRouteRoute: typeof DashboardOrganizationsAddRouteRouteWithChildren
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
}

const DashboardOrganizationsRouteRouteChildren: DashboardOrganizationsRouteRouteChildren =
  {
    DashboardOrganizationsOrganizationIdRouteRoute:
      DashboardOrganizationsOrganizationIdRouteRouteWithChildren,
    DashboardOrganizationsAddRouteRoute:
      DashboardOrganizationsAddRouteRouteWithChildren,
    DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
  }

const DashboardOrganizationsRouteRouteWithChildren =
  DashboardOrganizationsRouteRoute._addFileChildren(
    DashboardOrganizationsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAdministrationRouteRoute: typeof DashboardAdministrationRouteRouteWithChildren
  DashboardOrganizationsRouteRoute: typeof DashboardOrganizationsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdministrationRouteRoute:
    DashboardAdministrationRouteRouteWithChildren,
  DashboardOrganizationsRouteRoute:
    DashboardOrganizationsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/administration': typeof DashboardAdministrationRouteRouteWithChildren
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRouteWithChildren
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/administration/users': typeof DashboardAdministrationUsersRouteRouteWithChildren
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRouteRouteWithChildren
  '/dashboard/organizations/add': typeof DashboardOrganizationsAddRouteRouteWithChildren
  '/dashboard/administration/': typeof DashboardAdministrationIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/administration/users/$userId': typeof DashboardAdministrationUsersUserIdRouteRouteWithChildren
  '/dashboard/administration/users/add': typeof DashboardAdministrationUsersAddRouteRouteWithChildren
  '/dashboard/organizations/$organizationId/edit': typeof DashboardOrganizationsOrganizationIdEditRouteRouteWithChildren
  '/dashboard/administration/users/': typeof DashboardAdministrationUsersIndexRoute
  '/dashboard/organizations/$organizationId/': typeof DashboardOrganizationsOrganizationIdIndexRoute
  '/dashboard/organizations/add/': typeof DashboardOrganizationsAddIndexRoute
  '/dashboard/administration/users/$userId/edit': typeof DashboardAdministrationUsersUserIdEditRouteRouteWithChildren
  '/dashboard/administration/users/$userId/': typeof DashboardAdministrationUsersUserIdIndexRoute
  '/dashboard/administration/users/add/': typeof DashboardAdministrationUsersAddIndexRoute
  '/dashboard/organizations/$organizationId/edit/': typeof DashboardOrganizationsOrganizationIdEditIndexRoute
  '/dashboard/administration/users/$userId/edit/': typeof DashboardAdministrationUsersUserIdEditIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/administration': typeof DashboardAdministrationIndexRoute
  '/dashboard/organizations': typeof DashboardOrganizationsIndexRoute
  '/dashboard/administration/users': typeof DashboardAdministrationUsersIndexRoute
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdIndexRoute
  '/dashboard/organizations/add': typeof DashboardOrganizationsAddIndexRoute
  '/dashboard/administration/users/$userId': typeof DashboardAdministrationUsersUserIdIndexRoute
  '/dashboard/administration/users/add': typeof DashboardAdministrationUsersAddIndexRoute
  '/dashboard/organizations/$organizationId/edit': typeof DashboardOrganizationsOrganizationIdEditIndexRoute
  '/dashboard/administration/users/$userId/edit': typeof DashboardAdministrationUsersUserIdEditIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/administration': typeof DashboardAdministrationRouteRouteWithChildren
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/administration/users': typeof DashboardAdministrationUsersRouteRouteWithChildren
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRouteRouteWithChildren
  '/dashboard/organizations/add': typeof DashboardOrganizationsAddRouteRouteWithChildren
  '/dashboard/administration/': typeof DashboardAdministrationIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/administration/users/$userId': typeof DashboardAdministrationUsersUserIdRouteRouteWithChildren
  '/dashboard/administration/users/add': typeof DashboardAdministrationUsersAddRouteRouteWithChildren
  '/dashboard/organizations/$organizationId/edit': typeof DashboardOrganizationsOrganizationIdEditRouteRouteWithChildren
  '/dashboard/administration/users/': typeof DashboardAdministrationUsersIndexRoute
  '/dashboard/organizations/$organizationId/': typeof DashboardOrganizationsOrganizationIdIndexRoute
  '/dashboard/organizations/add/': typeof DashboardOrganizationsAddIndexRoute
  '/dashboard/administration/users/$userId/edit': typeof DashboardAdministrationUsersUserIdEditRouteRouteWithChildren
  '/dashboard/administration/users/$userId/': typeof DashboardAdministrationUsersUserIdIndexRoute
  '/dashboard/administration/users/add/': typeof DashboardAdministrationUsersAddIndexRoute
  '/dashboard/organizations/$organizationId/edit/': typeof DashboardOrganizationsOrganizationIdEditIndexRoute
  '/dashboard/administration/users/$userId/edit/': typeof DashboardAdministrationUsersUserIdEditIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/administration'
    | '/dashboard/organizations'
    | '/signin'
    | '/signup'
    | '/dashboard/'
    | '/dashboard/administration/users'
    | '/dashboard/organizations/$organizationId'
    | '/dashboard/organizations/add'
    | '/dashboard/administration/'
    | '/dashboard/organizations/'
    | '/dashboard/administration/users/$userId'
    | '/dashboard/administration/users/add'
    | '/dashboard/organizations/$organizationId/edit'
    | '/dashboard/administration/users/'
    | '/dashboard/organizations/$organizationId/'
    | '/dashboard/organizations/add/'
    | '/dashboard/administration/users/$userId/edit'
    | '/dashboard/administration/users/$userId/'
    | '/dashboard/administration/users/add/'
    | '/dashboard/organizations/$organizationId/edit/'
    | '/dashboard/administration/users/$userId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/dashboard/administration'
    | '/dashboard/organizations'
    | '/dashboard/administration/users'
    | '/dashboard/organizations/$organizationId'
    | '/dashboard/organizations/add'
    | '/dashboard/administration/users/$userId'
    | '/dashboard/administration/users/add'
    | '/dashboard/organizations/$organizationId/edit'
    | '/dashboard/administration/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/dashboard/administration'
    | '/dashboard/organizations'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/dashboard/'
    | '/dashboard/administration/users'
    | '/dashboard/organizations/$organizationId'
    | '/dashboard/organizations/add'
    | '/dashboard/administration/'
    | '/dashboard/organizations/'
    | '/dashboard/administration/users/$userId'
    | '/dashboard/administration/users/add'
    | '/dashboard/organizations/$organizationId/edit'
    | '/dashboard/administration/users/'
    | '/dashboard/organizations/$organizationId/'
    | '/dashboard/organizations/add/'
    | '/dashboard/administration/users/$userId/edit'
    | '/dashboard/administration/users/$userId/'
    | '/dashboard/administration/users/add/'
    | '/dashboard/organizations/$organizationId/edit/'
    | '/dashboard/administration/users/$userId/edit/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/signin",
        "/(auth)/signup"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/administration",
        "/dashboard/organizations",
        "/dashboard/"
      ]
    },
    "/dashboard/administration": {
      "filePath": "dashboard/administration/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/administration/users",
        "/dashboard/administration/"
      ]
    },
    "/dashboard/organizations": {
      "filePath": "dashboard/organizations/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/organizations/$organizationId",
        "/dashboard/organizations/add",
        "/dashboard/organizations/"
      ]
    },
    "/(auth)/signin": {
      "filePath": "(auth)/signin.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/signup": {
      "filePath": "(auth)/signup.tsx",
      "parent": "/(auth)"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/administration/users": {
      "filePath": "dashboard/administration/users/route.tsx",
      "parent": "/dashboard/administration",
      "children": [
        "/dashboard/administration/users/$userId",
        "/dashboard/administration/users/add",
        "/dashboard/administration/users/"
      ]
    },
    "/dashboard/organizations/$organizationId": {
      "filePath": "dashboard/organizations/$organizationId/route.tsx",
      "parent": "/dashboard/organizations",
      "children": [
        "/dashboard/organizations/$organizationId/edit",
        "/dashboard/organizations/$organizationId/"
      ]
    },
    "/dashboard/organizations/add": {
      "filePath": "dashboard/organizations/add/route.tsx",
      "parent": "/dashboard/organizations",
      "children": [
        "/dashboard/organizations/add/"
      ]
    },
    "/dashboard/administration/": {
      "filePath": "dashboard/administration/index.tsx",
      "parent": "/dashboard/administration"
    },
    "/dashboard/organizations/": {
      "filePath": "dashboard/organizations/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/administration/users/$userId": {
      "filePath": "dashboard/administration/users/$userId/route.tsx",
      "parent": "/dashboard/administration/users",
      "children": [
        "/dashboard/administration/users/$userId/edit",
        "/dashboard/administration/users/$userId/"
      ]
    },
    "/dashboard/administration/users/add": {
      "filePath": "dashboard/administration/users/add/route.tsx",
      "parent": "/dashboard/administration/users",
      "children": [
        "/dashboard/administration/users/add/"
      ]
    },
    "/dashboard/organizations/$organizationId/edit": {
      "filePath": "dashboard/organizations/$organizationId/edit/route.tsx",
      "parent": "/dashboard/organizations/$organizationId",
      "children": [
        "/dashboard/organizations/$organizationId/edit/"
      ]
    },
    "/dashboard/administration/users/": {
      "filePath": "dashboard/administration/users/index.tsx",
      "parent": "/dashboard/administration/users"
    },
    "/dashboard/organizations/$organizationId/": {
      "filePath": "dashboard/organizations/$organizationId/index.tsx",
      "parent": "/dashboard/organizations/$organizationId"
    },
    "/dashboard/organizations/add/": {
      "filePath": "dashboard/organizations/add/index.tsx",
      "parent": "/dashboard/organizations/add"
    },
    "/dashboard/administration/users/$userId/edit": {
      "filePath": "dashboard/administration/users/$userId/edit/route.tsx",
      "parent": "/dashboard/administration/users/$userId",
      "children": [
        "/dashboard/administration/users/$userId/edit/"
      ]
    },
    "/dashboard/administration/users/$userId/": {
      "filePath": "dashboard/administration/users/$userId/index.tsx",
      "parent": "/dashboard/administration/users/$userId"
    },
    "/dashboard/administration/users/add/": {
      "filePath": "dashboard/administration/users/add/index.tsx",
      "parent": "/dashboard/administration/users/add"
    },
    "/dashboard/organizations/$organizationId/edit/": {
      "filePath": "dashboard/organizations/$organizationId/edit/index.tsx",
      "parent": "/dashboard/organizations/$organizationId/edit"
    },
    "/dashboard/administration/users/$userId/edit/": {
      "filePath": "dashboard/administration/users/$userId/edit/index.tsx",
      "parent": "/dashboard/administration/users/$userId/edit"
    }
  }
}
ROUTE_MANIFEST_END */
