/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as authSignupImport } from './routes/(auth)/signup'
import { Route as authSigninImport } from './routes/(auth)/signin'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users/route'
import { Route as DashboardOrganizationsRouteImport } from './routes/dashboard/organizations/route'
import { Route as DashboardUsersIndexImport } from './routes/dashboard/users/index'
import { Route as DashboardOrganizationsIndexImport } from './routes/dashboard/organizations/index'
import { Route as DashboardUsersAddRouteImport } from './routes/dashboard/users/add/route'
import { Route as DashboardUsersUserIdRouteImport } from './routes/dashboard/users/$userId/route'
import { Route as DashboardOrganizationsAddRouteImport } from './routes/dashboard/organizations/add/route'
import { Route as DashboardOrganizationsOrganizationIdRouteImport } from './routes/dashboard/organizations/$organizationId/route'
import { Route as DashboardUsersAddIndexImport } from './routes/dashboard/users/add/index'
import { Route as DashboardUsersUserIdIndexImport } from './routes/dashboard/users/$userId/index'
import { Route as DashboardOrganizationsAddIndexImport } from './routes/dashboard/organizations/add/index'
import { Route as DashboardOrganizationsOrganizationIdIndexImport } from './routes/dashboard/organizations/$organizationId/index'
import { Route as DashboardUsersUserIdEditRouteImport } from './routes/dashboard/users/$userId/edit/route'
import { Route as DashboardOrganizationsOrganizationIdEditRouteImport } from './routes/dashboard/organizations/$organizationId/edit/route'
import { Route as DashboardUsersUserIdEditIndexImport } from './routes/dashboard/users/$userId/edit/index'
import { Route as DashboardOrganizationsOrganizationIdEditIndexImport } from './routes/dashboard/organizations/$organizationId/edit/index'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const authSignupRoute = authSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)

const authSigninRoute = authSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)

const DashboardUsersRouteRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardOrganizationsRouteRoute =
  DashboardOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardUsersIndexRoute = DashboardUsersIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)

const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardUsersAddRouteRoute = DashboardUsersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)

const DashboardUsersUserIdRouteRoute = DashboardUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)

const DashboardOrganizationsAddRouteRoute =
  DashboardOrganizationsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardOrganizationsOrganizationIdRouteRoute =
  DashboardOrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)

const DashboardUsersAddIndexRoute = DashboardUsersAddIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersAddRouteRoute,
} as any)

const DashboardUsersUserIdIndexRoute = DashboardUsersUserIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersUserIdRouteRoute,
} as any)

const DashboardOrganizationsAddIndexRoute =
  DashboardOrganizationsAddIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsAddRouteRoute,
  } as any)

const DashboardOrganizationsOrganizationIdIndexRoute =
  DashboardOrganizationsOrganizationIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsOrganizationIdRouteRoute,
  } as any)

const DashboardUsersUserIdEditRouteRoute =
  DashboardUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardUsersUserIdRouteRoute,
  } as any)

const DashboardOrganizationsOrganizationIdEditRouteRoute =
  DashboardOrganizationsOrganizationIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardOrganizationsOrganizationIdRouteRoute,
  } as any)

const DashboardUsersUserIdEditIndexRoute =
  DashboardUsersUserIdEditIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardUsersUserIdEditRouteRoute,
  } as any)

const DashboardOrganizationsOrganizationIdEditIndexRoute =
  DashboardOrganizationsOrganizationIdEditIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsOrganizationIdEditRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/organizations': {
      id: '/dashboard/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DashboardOrganizationsRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupImport
      parentRoute: typeof authRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/organizations/$organizationId': {
      id: '/dashboard/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/dashboard/organizations/$organizationId'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdRouteImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/organizations/add': {
      id: '/dashboard/organizations/add'
      path: '/add'
      fullPath: '/dashboard/organizations/add'
      preLoaderRoute: typeof DashboardOrganizationsAddRouteImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/users/$userId': {
      id: '/dashboard/users/$userId'
      path: '/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardUsersRouteImport
    }
    '/dashboard/users/add': {
      id: '/dashboard/users/add'
      path: '/add'
      fullPath: '/dashboard/users/add'
      preLoaderRoute: typeof DashboardUsersAddRouteImport
      parentRoute: typeof DashboardUsersRouteImport
    }
    '/dashboard/organizations/': {
      id: '/dashboard/organizations/'
      path: '/'
      fullPath: '/dashboard/organizations/'
      preLoaderRoute: typeof DashboardOrganizationsIndexImport
      parentRoute: typeof DashboardOrganizationsRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexImport
      parentRoute: typeof DashboardUsersRouteImport
    }
    '/dashboard/organizations/$organizationId/edit': {
      id: '/dashboard/organizations/$organizationId/edit'
      path: '/edit'
      fullPath: '/dashboard/organizations/$organizationId/edit'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdEditRouteImport
      parentRoute: typeof DashboardOrganizationsOrganizationIdRouteImport
    }
    '/dashboard/users/$userId/edit': {
      id: '/dashboard/users/$userId/edit'
      path: '/edit'
      fullPath: '/dashboard/users/$userId/edit'
      preLoaderRoute: typeof DashboardUsersUserIdEditRouteImport
      parentRoute: typeof DashboardUsersUserIdRouteImport
    }
    '/dashboard/organizations/$organizationId/': {
      id: '/dashboard/organizations/$organizationId/'
      path: '/'
      fullPath: '/dashboard/organizations/$organizationId/'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdIndexImport
      parentRoute: typeof DashboardOrganizationsOrganizationIdRouteImport
    }
    '/dashboard/organizations/add/': {
      id: '/dashboard/organizations/add/'
      path: '/'
      fullPath: '/dashboard/organizations/add/'
      preLoaderRoute: typeof DashboardOrganizationsAddIndexImport
      parentRoute: typeof DashboardOrganizationsAddRouteImport
    }
    '/dashboard/users/$userId/': {
      id: '/dashboard/users/$userId/'
      path: '/'
      fullPath: '/dashboard/users/$userId/'
      preLoaderRoute: typeof DashboardUsersUserIdIndexImport
      parentRoute: typeof DashboardUsersUserIdRouteImport
    }
    '/dashboard/users/add/': {
      id: '/dashboard/users/add/'
      path: '/'
      fullPath: '/dashboard/users/add/'
      preLoaderRoute: typeof DashboardUsersAddIndexImport
      parentRoute: typeof DashboardUsersAddRouteImport
    }
    '/dashboard/organizations/$organizationId/edit/': {
      id: '/dashboard/organizations/$organizationId/edit/'
      path: '/'
      fullPath: '/dashboard/organizations/$organizationId/edit/'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdEditIndexImport
      parentRoute: typeof DashboardOrganizationsOrganizationIdEditRouteImport
    }
    '/dashboard/users/$userId/edit/': {
      id: '/dashboard/users/$userId/edit/'
      path: '/'
      fullPath: '/dashboard/users/$userId/edit/'
      preLoaderRoute: typeof DashboardUsersUserIdEditIndexImport
      parentRoute: typeof DashboardUsersUserIdEditRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardOrganizationsOrganizationIdEditRouteRouteChildren {
  DashboardOrganizationsOrganizationIdEditIndexRoute: typeof DashboardOrganizationsOrganizationIdEditIndexRoute
}

const DashboardOrganizationsOrganizationIdEditRouteRouteChildren: DashboardOrganizationsOrganizationIdEditRouteRouteChildren =
  {
    DashboardOrganizationsOrganizationIdEditIndexRoute:
      DashboardOrganizationsOrganizationIdEditIndexRoute,
  }

const DashboardOrganizationsOrganizationIdEditRouteRouteWithChildren =
  DashboardOrganizationsOrganizationIdEditRouteRoute._addFileChildren(
    DashboardOrganizationsOrganizationIdEditRouteRouteChildren,
  )

interface DashboardOrganizationsOrganizationIdRouteRouteChildren {
  DashboardOrganizationsOrganizationIdEditRouteRoute: typeof DashboardOrganizationsOrganizationIdEditRouteRouteWithChildren
  DashboardOrganizationsOrganizationIdIndexRoute: typeof DashboardOrganizationsOrganizationIdIndexRoute
}

const DashboardOrganizationsOrganizationIdRouteRouteChildren: DashboardOrganizationsOrganizationIdRouteRouteChildren =
  {
    DashboardOrganizationsOrganizationIdEditRouteRoute:
      DashboardOrganizationsOrganizationIdEditRouteRouteWithChildren,
    DashboardOrganizationsOrganizationIdIndexRoute:
      DashboardOrganizationsOrganizationIdIndexRoute,
  }

const DashboardOrganizationsOrganizationIdRouteRouteWithChildren =
  DashboardOrganizationsOrganizationIdRouteRoute._addFileChildren(
    DashboardOrganizationsOrganizationIdRouteRouteChildren,
  )

interface DashboardOrganizationsAddRouteRouteChildren {
  DashboardOrganizationsAddIndexRoute: typeof DashboardOrganizationsAddIndexRoute
}

const DashboardOrganizationsAddRouteRouteChildren: DashboardOrganizationsAddRouteRouteChildren =
  {
    DashboardOrganizationsAddIndexRoute: DashboardOrganizationsAddIndexRoute,
  }

const DashboardOrganizationsAddRouteRouteWithChildren =
  DashboardOrganizationsAddRouteRoute._addFileChildren(
    DashboardOrganizationsAddRouteRouteChildren,
  )

interface DashboardOrganizationsRouteRouteChildren {
  DashboardOrganizationsOrganizationIdRouteRoute: typeof DashboardOrganizationsOrganizationIdRouteRouteWithChildren
  DashboardOrganizationsAddRouteRoute: typeof DashboardOrganizationsAddRouteRouteWithChildren
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
}

const DashboardOrganizationsRouteRouteChildren: DashboardOrganizationsRouteRouteChildren =
  {
    DashboardOrganizationsOrganizationIdRouteRoute:
      DashboardOrganizationsOrganizationIdRouteRouteWithChildren,
    DashboardOrganizationsAddRouteRoute:
      DashboardOrganizationsAddRouteRouteWithChildren,
    DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
  }

const DashboardOrganizationsRouteRouteWithChildren =
  DashboardOrganizationsRouteRoute._addFileChildren(
    DashboardOrganizationsRouteRouteChildren,
  )

interface DashboardUsersUserIdEditRouteRouteChildren {
  DashboardUsersUserIdEditIndexRoute: typeof DashboardUsersUserIdEditIndexRoute
}

const DashboardUsersUserIdEditRouteRouteChildren: DashboardUsersUserIdEditRouteRouteChildren =
  {
    DashboardUsersUserIdEditIndexRoute: DashboardUsersUserIdEditIndexRoute,
  }

const DashboardUsersUserIdEditRouteRouteWithChildren =
  DashboardUsersUserIdEditRouteRoute._addFileChildren(
    DashboardUsersUserIdEditRouteRouteChildren,
  )

interface DashboardUsersUserIdRouteRouteChildren {
  DashboardUsersUserIdEditRouteRoute: typeof DashboardUsersUserIdEditRouteRouteWithChildren
  DashboardUsersUserIdIndexRoute: typeof DashboardUsersUserIdIndexRoute
}

const DashboardUsersUserIdRouteRouteChildren: DashboardUsersUserIdRouteRouteChildren =
  {
    DashboardUsersUserIdEditRouteRoute:
      DashboardUsersUserIdEditRouteRouteWithChildren,
    DashboardUsersUserIdIndexRoute: DashboardUsersUserIdIndexRoute,
  }

const DashboardUsersUserIdRouteRouteWithChildren =
  DashboardUsersUserIdRouteRoute._addFileChildren(
    DashboardUsersUserIdRouteRouteChildren,
  )

interface DashboardUsersAddRouteRouteChildren {
  DashboardUsersAddIndexRoute: typeof DashboardUsersAddIndexRoute
}

const DashboardUsersAddRouteRouteChildren: DashboardUsersAddRouteRouteChildren =
  {
    DashboardUsersAddIndexRoute: DashboardUsersAddIndexRoute,
  }

const DashboardUsersAddRouteRouteWithChildren =
  DashboardUsersAddRouteRoute._addFileChildren(
    DashboardUsersAddRouteRouteChildren,
  )

interface DashboardUsersRouteRouteChildren {
  DashboardUsersUserIdRouteRoute: typeof DashboardUsersUserIdRouteRouteWithChildren
  DashboardUsersAddRouteRoute: typeof DashboardUsersAddRouteRouteWithChildren
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardUsersRouteRouteChildren: DashboardUsersRouteRouteChildren = {
  DashboardUsersUserIdRouteRoute: DashboardUsersUserIdRouteRouteWithChildren,
  DashboardUsersAddRouteRoute: DashboardUsersAddRouteRouteWithChildren,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardUsersRouteRouteWithChildren =
  DashboardUsersRouteRoute._addFileChildren(DashboardUsersRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardOrganizationsRouteRoute: typeof DashboardOrganizationsRouteRouteWithChildren
  DashboardUsersRouteRoute: typeof DashboardUsersRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardOrganizationsRouteRoute:
    DashboardOrganizationsRouteRouteWithChildren,
  DashboardUsersRouteRoute: DashboardUsersRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteRouteWithChildren
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRouteRouteWithChildren
  '/dashboard/organizations/add': typeof DashboardOrganizationsAddRouteRouteWithChildren
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRouteRouteWithChildren
  '/dashboard/users/add': typeof DashboardUsersAddRouteRouteWithChildren
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/organizations/$organizationId/edit': typeof DashboardOrganizationsOrganizationIdEditRouteRouteWithChildren
  '/dashboard/users/$userId/edit': typeof DashboardUsersUserIdEditRouteRouteWithChildren
  '/dashboard/organizations/$organizationId/': typeof DashboardOrganizationsOrganizationIdIndexRoute
  '/dashboard/organizations/add/': typeof DashboardOrganizationsAddIndexRoute
  '/dashboard/users/$userId/': typeof DashboardUsersUserIdIndexRoute
  '/dashboard/users/add/': typeof DashboardUsersAddIndexRoute
  '/dashboard/organizations/$organizationId/edit/': typeof DashboardOrganizationsOrganizationIdEditIndexRoute
  '/dashboard/users/$userId/edit/': typeof DashboardUsersUserIdEditIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/organizations': typeof DashboardOrganizationsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdIndexRoute
  '/dashboard/organizations/add': typeof DashboardOrganizationsAddIndexRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdIndexRoute
  '/dashboard/users/add': typeof DashboardUsersAddIndexRoute
  '/dashboard/organizations/$organizationId/edit': typeof DashboardOrganizationsOrganizationIdEditIndexRoute
  '/dashboard/users/$userId/edit': typeof DashboardUsersUserIdEditIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRouteRouteWithChildren
  '/dashboard/organizations/add': typeof DashboardOrganizationsAddRouteRouteWithChildren
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRouteRouteWithChildren
  '/dashboard/users/add': typeof DashboardUsersAddRouteRouteWithChildren
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/organizations/$organizationId/edit': typeof DashboardOrganizationsOrganizationIdEditRouteRouteWithChildren
  '/dashboard/users/$userId/edit': typeof DashboardUsersUserIdEditRouteRouteWithChildren
  '/dashboard/organizations/$organizationId/': typeof DashboardOrganizationsOrganizationIdIndexRoute
  '/dashboard/organizations/add/': typeof DashboardOrganizationsAddIndexRoute
  '/dashboard/users/$userId/': typeof DashboardUsersUserIdIndexRoute
  '/dashboard/users/add/': typeof DashboardUsersAddIndexRoute
  '/dashboard/organizations/$organizationId/edit/': typeof DashboardOrganizationsOrganizationIdEditIndexRoute
  '/dashboard/users/$userId/edit/': typeof DashboardUsersUserIdEditIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/organizations'
    | '/dashboard/users'
    | '/signin'
    | '/signup'
    | '/dashboard/'
    | '/dashboard/organizations/$organizationId'
    | '/dashboard/organizations/add'
    | '/dashboard/users/$userId'
    | '/dashboard/users/add'
    | '/dashboard/organizations/'
    | '/dashboard/users/'
    | '/dashboard/organizations/$organizationId/edit'
    | '/dashboard/users/$userId/edit'
    | '/dashboard/organizations/$organizationId/'
    | '/dashboard/organizations/add/'
    | '/dashboard/users/$userId/'
    | '/dashboard/users/add/'
    | '/dashboard/organizations/$organizationId/edit/'
    | '/dashboard/users/$userId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/dashboard/organizations'
    | '/dashboard/users'
    | '/dashboard/organizations/$organizationId'
    | '/dashboard/organizations/add'
    | '/dashboard/users/$userId'
    | '/dashboard/users/add'
    | '/dashboard/organizations/$organizationId/edit'
    | '/dashboard/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/dashboard/organizations'
    | '/dashboard/users'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/dashboard/'
    | '/dashboard/organizations/$organizationId'
    | '/dashboard/organizations/add'
    | '/dashboard/users/$userId'
    | '/dashboard/users/add'
    | '/dashboard/organizations/'
    | '/dashboard/users/'
    | '/dashboard/organizations/$organizationId/edit'
    | '/dashboard/users/$userId/edit'
    | '/dashboard/organizations/$organizationId/'
    | '/dashboard/organizations/add/'
    | '/dashboard/users/$userId/'
    | '/dashboard/users/add/'
    | '/dashboard/organizations/$organizationId/edit/'
    | '/dashboard/users/$userId/edit/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/signin",
        "/(auth)/signup"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/organizations",
        "/dashboard/users",
        "/dashboard/"
      ]
    },
    "/dashboard/organizations": {
      "filePath": "dashboard/organizations/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/organizations/$organizationId",
        "/dashboard/organizations/add",
        "/dashboard/organizations/"
      ]
    },
    "/dashboard/users": {
      "filePath": "dashboard/users/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/users/$userId",
        "/dashboard/users/add",
        "/dashboard/users/"
      ]
    },
    "/(auth)/signin": {
      "filePath": "(auth)/signin.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/signup": {
      "filePath": "(auth)/signup.tsx",
      "parent": "/(auth)"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/organizations/$organizationId": {
      "filePath": "dashboard/organizations/$organizationId/route.tsx",
      "parent": "/dashboard/organizations",
      "children": [
        "/dashboard/organizations/$organizationId/edit",
        "/dashboard/organizations/$organizationId/"
      ]
    },
    "/dashboard/organizations/add": {
      "filePath": "dashboard/organizations/add/route.tsx",
      "parent": "/dashboard/organizations",
      "children": [
        "/dashboard/organizations/add/"
      ]
    },
    "/dashboard/users/$userId": {
      "filePath": "dashboard/users/$userId/route.tsx",
      "parent": "/dashboard/users",
      "children": [
        "/dashboard/users/$userId/edit",
        "/dashboard/users/$userId/"
      ]
    },
    "/dashboard/users/add": {
      "filePath": "dashboard/users/add/route.tsx",
      "parent": "/dashboard/users",
      "children": [
        "/dashboard/users/add/"
      ]
    },
    "/dashboard/organizations/": {
      "filePath": "dashboard/organizations/index.tsx",
      "parent": "/dashboard/organizations"
    },
    "/dashboard/users/": {
      "filePath": "dashboard/users/index.tsx",
      "parent": "/dashboard/users"
    },
    "/dashboard/organizations/$organizationId/edit": {
      "filePath": "dashboard/organizations/$organizationId/edit/route.tsx",
      "parent": "/dashboard/organizations/$organizationId",
      "children": [
        "/dashboard/organizations/$organizationId/edit/"
      ]
    },
    "/dashboard/users/$userId/edit": {
      "filePath": "dashboard/users/$userId/edit/route.tsx",
      "parent": "/dashboard/users/$userId",
      "children": [
        "/dashboard/users/$userId/edit/"
      ]
    },
    "/dashboard/organizations/$organizationId/": {
      "filePath": "dashboard/organizations/$organizationId/index.tsx",
      "parent": "/dashboard/organizations/$organizationId"
    },
    "/dashboard/organizations/add/": {
      "filePath": "dashboard/organizations/add/index.tsx",
      "parent": "/dashboard/organizations/add"
    },
    "/dashboard/users/$userId/": {
      "filePath": "dashboard/users/$userId/index.tsx",
      "parent": "/dashboard/users/$userId"
    },
    "/dashboard/users/add/": {
      "filePath": "dashboard/users/add/index.tsx",
      "parent": "/dashboard/users/add"
    },
    "/dashboard/organizations/$organizationId/edit/": {
      "filePath": "dashboard/organizations/$organizationId/edit/index.tsx",
      "parent": "/dashboard/organizations/$organizationId/edit"
    },
    "/dashboard/users/$userId/edit/": {
      "filePath": "dashboard/users/$userId/edit/index.tsx",
      "parent": "/dashboard/users/$userId/edit"
    }
  }
}
ROUTE_MANIFEST_END */
